CREATE TABLE IF NOT EXISTS stories (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    location VARCHAR(100),
    author_id UUID NOT NULL,
    likes_count INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS story_tags (
    story_id UUID REFERENCES stories(id) ON DELETE CASCADE,
    tag VARCHAR(50),
    PRIMARY KEY (story_id, tag)
);

CREATE TABLE IF NOT EXISTS comments (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    content TEXT NOT NULL,
    author_id UUID NOT NULL,
    story_id UUID REFERENCES stories(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS likes (
    user_id UUID NOT NULL,
    story_id UUID REFERENCES stories(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, story_id)
);

CREATE TABLE IF NOT EXISTS itineraries (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    author_id UUID NOT NULL,
    likes_count INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS itinerary_destinations (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    itinerary_id UUID REFERENCES itineraries(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS itinerary_activities (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    destination_id UUID REFERENCES itinerary_destinations (id) ON DELETE CASCADE,
    activity TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS itinerary_comments (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    content TEXT NOT NULL,
    author_id UUID NOT NULL,
    itinerary_id UUID REFERENCES itineraries(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS destinations (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    description TEXT,
    best_time_to_visit VARCHAR(100),
    average_cost_per_day DECIMAL(10, 2),
    currency VARCHAR(3),
    language VARCHAR(50),
    popularity_score INTEGER DEFAULT 25,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS destination_activities (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    destination_id UUID REFERENCES destinations(id) ON DELETE CASCADE,
    activity TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS top_attractions (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    destination_id UUID REFERENCES destinations(id) ON DELETE CASCADE,
    attraction TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    sender_id UUID NOT NULL,
    recipient_id UUID NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS travel_tips (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(50),
    author_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
